using CrushEase.Data;
using CrushEase.Models;
using CrushEase.Utils;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CrushEase.Services;

/// <summary>
/// Service for generating professional PDF invoices
/// </summary>
public static class InvoiceGenerator
{
    static InvoiceGenerator()
    {
        // Set QuestPDF license to Community (free for open-source/personal use)
        QuestPDF.Settings.License = LicenseType.Community;
    }
    
    /// <summary>
    /// Generate invoice for a sale transaction
    /// </summary>
    public static InvoiceResult GenerateSaleInvoice(Sale sale)
    {
        try
        {
            // Get company settings
            var companySettings = CompanySettingsRepository.Get();
            if (companySettings == null || string.IsNullOrEmpty(companySettings.CompanyName))
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Company settings not configured. Please configure company details first." 
                };
            }
            
            // Get buyer details
            var buyer = BuyerRepository.GetById(sale.BuyerId);
            if (buyer == null)
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Buyer not found." 
                };
            }
            
            // Get material details
            var material = MaterialRepository.GetById(sale.MaterialId);
            if (material == null)
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Material not found." 
                };
            }
            
            // Generate invoice number
            var existingInvoice = InvoiceMetadataRepository.GetByTransaction("Sale", sale.SaleId);
            string invoiceNumber;
            
            if (existingInvoice != null)
            {
                invoiceNumber = existingInvoice.InvoiceNumber;
            }
            else
            {
                invoiceNumber = InvoiceMetadataRepository.GenerateInvoiceNumber(companySettings.InvoicePrefix);
            }
            
            // Create PDF
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A5);
                    page.Margin(20);
                    page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Segoe UI"));
                    
                    page.Header().Element(c => ComposeHeader(c, companySettings, invoiceNumber, sale.SaleDate));
                    page.Content().Element(c => ComposeSaleContent(c, sale, buyer, material, companySettings));
                    page.Footer().Column(col =>
                    {
                        col.Item().AlignCenter().Text(x =>
                        {
                            x.Span("Generated by CrushEase Ledger on ");
                            x.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                        });
                        col.Item().PaddingTop(5).AlignCenter().Text(x =>
                        {
                            x.Span("Built by NMD").FontSize(7).Italic().FontColor(Colors.Grey.Medium);
                        });
                        col.Item().PaddingTop(3).AlignCenter().Text(x =>
                        {
                            x.Span("* Not a GST Invoice *").FontSize(8).Bold().FontColor(Colors.Red.Medium);
                        });
                    });
                });
            });
            
            // Generate file path
            string invoicesFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "CrushEase Invoices"
            );
            Directory.CreateDirectory(invoicesFolder);
            
            string fileName = $"{invoiceNumber.Replace("/", "-")}_{buyer.BuyerName.Replace(" ", "_")}.pdf";
            string filePath = Path.Combine(invoicesFolder, fileName);
            
            // Save PDF
            document.GeneratePdf(filePath);
            
            // Save metadata if new invoice
            if (existingInvoice == null)
            {
                var metadata = new InvoiceMetadata
                {
                    InvoiceNumber = invoiceNumber,
                    TransactionType = "Sale",
                    TransactionId = sale.SaleId,
                    GeneratedDate = DateTime.Now,
                    GeneratedBy = "System",
                    FilePath = filePath
                };
                InvoiceMetadataRepository.Save(metadata);
            }
            
            Logger.LogInfo($"Invoice generated: {invoiceNumber}");
            
            return new InvoiceResult
            {
                Success = true,
                InvoiceNumber = invoiceNumber,
                FilePath = filePath,
                PdfDocument = document
            };
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate invoice");
            string detailedError = ex.Message;
            if (ex.InnerException != null)
            {
                detailedError += $" | Inner: {ex.InnerException.Message}";
            }
            detailedError += $" | Type: {ex.GetType().Name}";
            
            return new InvoiceResult
            {
                Success = false,
                ErrorMessage = $"Error generating invoice: {detailedError}"
            };
        }
    }
    
    private static void ComposeHeader(IContainer container, CompanySettings settings, string invoiceNumber, DateTime invoiceDate)
    {
        container.Column(column =>
        {
            column.Spacing(3);
            
            // Company info - compact for A5
            column.Item().Row(row =>
            {
                // Left: Company details
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(settings.CompanyName)
                        .FontSize(12)
                        .Bold();
                    
                    if (!string.IsNullOrEmpty(settings.Address))
                        col.Item().Text(settings.Address).FontSize(7);
                    
                    var contact = new List<string>();
                    if (!string.IsNullOrEmpty(settings.Phone))
                        contact.Add($"Ph: {settings.Phone}");
                    if (!string.IsNullOrEmpty(settings.Email))
                        contact.Add(settings.Email);
                    if (contact.Count > 0)
                        col.Item().Text(string.Join(" | ", contact)).FontSize(7);
                    
                    if (!string.IsNullOrEmpty(settings.GSTNumber))
                        col.Item().Text($"GST: {settings.GSTNumber}").FontSize(7);
                });
                
                // Right: Logo (if exists) - smaller for A5
                if (settings.LogoImage != null && settings.LogoImage.Length > 0)
                {
                    row.ConstantItem(50).Image(settings.LogoImage).FitArea();
                }
            });
            
            column.Item().PaddingTop(2).LineHorizontal(1).LineColor(Colors.Black);
            
            // Invoice title and details - compact
            column.Item().PaddingVertical(4).Row(row =>
            {
                row.RelativeItem().Text("INVOICE").FontSize(14).Bold();
                row.RelativeItem().AlignRight().Column(c =>
                {
                    c.Item().AlignRight().Text($"No: {invoiceNumber}").FontSize(8).Bold();
                    c.Item().AlignRight().Text($"Date: {invoiceDate:dd-MMM-yyyy}").FontSize(8);
                });
            });
            
            column.Item().LineHorizontal(1).LineColor(Colors.Black);
        });
    }
    
    private static void ComposeSaleContent(IContainer container, Sale sale, Buyer buyer, Material material, CompanySettings settings)
    {
        container.Column(column =>
        {
            column.Spacing(6);
            
            // Bill To section - compact
            column.Item().Border(1).BorderColor(Colors.Black).Padding(5).Column(col =>
            {
                col.Item().Text("BILL TO:").Bold().FontSize(8);
                col.Item().PaddingTop(2).Column(c =>
                {
                    c.Item().Text(buyer.BuyerName).FontSize(9).Bold();
                    if (!string.IsNullOrEmpty(buyer.Contact))
                        c.Item().Text($"Contact: {buyer.Contact}").FontSize(7);
                });
            });
            
            // Invoice items table - compact
            column.Item().PaddingTop(5).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                });
                
                table.Header(header =>
                {
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .Text("Description").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignCenter().Text("Qty").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignCenter().Text("Rate").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignRight().Text("Amount").Bold().FontSize(8);
                });
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4).Column(col =>
                {
                    col.Item().Text(material.MaterialName).Bold().FontSize(8);
                    col.Item().Text($"Vehicle: {sale.VehicleNo}").FontSize(6).Italic();
                    
                    string unitInfo = sale.InputUnit == "MT" 
                        ? $"{sale.InputQuantity:F2} MT ({sale.CalculatedCFT:F2} CFT)"
                        : $"{sale.InputQuantity:F2} CFT";
                    col.Item().Text(unitInfo).FontSize(6).Italic();
                });
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignCenter().Text($"{sale.Quantity:F2}").FontSize(8);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignCenter().Text($"₹{sale.Rate:F2}").FontSize(8);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignRight().Text($"₹{sale.Amount:F2}").Bold().FontSize(8);
            });
            
            // Total - compact
            column.Item().PaddingTop(3).Border(1).BorderColor(Colors.Black).Padding(5).Row(row =>
            {
                row.RelativeItem().Text("TOTAL:").Bold().FontSize(10);
                row.ConstantItem(80).AlignRight().Text($"₹{sale.Amount:F2}").Bold().FontSize(10);
            });
            
            // Payment terms - compact
            column.Item().PaddingTop(8).Column(col =>
            {
                col.Item().Text("Payment Terms:").Bold().FontSize(7);
                col.Item().PaddingTop(2).Text(settings.PaymentTerms).FontSize(7);
            });
            
            if (!string.IsNullOrEmpty(settings.TermsAndConditions))
            {
                column.Item().PaddingTop(6).Column(col =>
                {
                    col.Item().Text("Terms & Conditions:").Bold().FontSize(7);
                    col.Item().PaddingTop(2).Text(settings.TermsAndConditions).FontSize(6);
                });
            }
            
            // Signature
            column.Item().PaddingTop(15).Row(row =>
            {
                row.RelativeItem();
                row.ConstantItem(100).Column(col =>
                {
                    col.Item().AlignCenter().Text("Authorized Sign").FontSize(7);
                    col.Item().PaddingTop(15).BorderTop(1).BorderColor(Colors.Black);
                });
            });
        });
    }
    
    /// <summary>
    /// Generate invoice for a purchase transaction
    /// </summary>
    public static InvoiceResult GeneratePurchaseInvoice(Purchase purchase)
    {
        try
        {
            var companySettings = CompanySettingsRepository.Get();
            if (companySettings == null || string.IsNullOrEmpty(companySettings.CompanyName))
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Company settings not configured." 
                };
            }
            
            var vendor = VendorRepository.GetById(purchase.VendorId);
            if (vendor == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Vendor not found." };
            }
            
            var material = MaterialRepository.GetById(purchase.MaterialId);
            if (material == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Material not found." };
            }
            
            var existingInvoice = InvoiceMetadataRepository.GetByTransaction("Purchase", purchase.PurchaseId);
            string invoiceNumber = existingInvoice?.InvoiceNumber 
                ?? InvoiceMetadataRepository.GenerateInvoiceNumber(companySettings.InvoicePrefix);
            
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A5);
                    page.Margin(20);
                    page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Segoe UI"));
                    
                    page.Header().Element(c => ComposeHeader(c, companySettings, invoiceNumber, purchase.PurchaseDate));
                    page.Content().Element(c => ComposePurchaseContent(c, purchase, vendor, material, companySettings));
                    page.Footer().Column(col =>
                    {
                        col.Item().AlignCenter().Text(x =>
                        {
                            x.Span("Generated by CrushEase Ledger on ");
                            x.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                        });
                        col.Item().PaddingTop(5).AlignCenter().Text(x =>
                        {
                            x.Span("Built by NMD").FontSize(7).Italic().FontColor(Colors.Grey.Medium);
                        });
                        col.Item().PaddingTop(3).AlignCenter().Text(x =>
                        {
                            x.Span("* Not a GST Invoice *").FontSize(8).Bold().FontColor(Colors.Red.Medium);
                        });
                    });
                });
            });
            
            string invoicesFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "CrushEase Invoices"
            );
            Directory.CreateDirectory(invoicesFolder);
            
            string fileName = $"{invoiceNumber.Replace("/", "-")}_{vendor.VendorName.Replace(" ", "_")}_Purchase.pdf";
            string filePath = Path.Combine(invoicesFolder, fileName);
            
            document.GeneratePdf(filePath);
            
            if (existingInvoice == null)
            {
                var metadata = new InvoiceMetadata
                {
                    InvoiceNumber = invoiceNumber,
                    TransactionType = "Purchase",
                    TransactionId = purchase.PurchaseId,
                    GeneratedDate = DateTime.Now,
                    GeneratedBy = "System",
                    FilePath = filePath
                };
                InvoiceMetadataRepository.Save(metadata);
            }
            
            Logger.LogInfo($"Purchase invoice generated: {invoiceNumber}");
            
            return new InvoiceResult
            {
                Success = true,
                InvoiceNumber = invoiceNumber,
                FilePath = filePath,
                PdfDocument = document
            };
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate purchase invoice");
            string detailedError = ex.Message;
            if (ex.InnerException != null)
            {
                detailedError += $" | Inner: {ex.InnerException.Message}";
            }
            detailedError += $" | Type: {ex.GetType().Name}";
            
            return new InvoiceResult
            {
                Success = false,
                ErrorMessage = $"Error generating purchase invoice: {detailedError}"
            };
        }
    }
    
    /// <summary>
    /// Generate receipt for a purchase transaction (payment + goods receipt)
    /// </summary>
    public static InvoiceResult GeneratePurchaseReceipt(Purchase purchase)
    {
        try
        {
            var companySettings = CompanySettingsRepository.Get();
            if (companySettings == null || string.IsNullOrEmpty(companySettings.CompanyName))
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Company settings not configured." 
                };
            }
            
            var vendor = VendorRepository.GetById(purchase.VendorId);
            if (vendor == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Vendor not found." };
            }
            
            var material = MaterialRepository.GetById(purchase.MaterialId);
            if (material == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Material not found." };
            }
            
            // Generate receipt number (using invoice system)
            var existingReceipt = InvoiceMetadataRepository.GetByTransaction("PurchaseReceipt", purchase.PurchaseId);
            string receiptNumber = existingReceipt?.InvoiceNumber 
                ?? InvoiceMetadataRepository.GenerateInvoiceNumber(companySettings.InvoicePrefix + "R");
            
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A5);
                    page.Margin(20);
                    page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Segoe UI"));
                    
                    page.Header().Element(c => ComposeReceiptHeader(c, companySettings, receiptNumber, purchase.PurchaseDate));
                    page.Content().Element(c => ComposePurchaseReceiptContent(c, purchase, vendor, material, companySettings));
                    page.Footer().Column(col =>
                    {
                        col.Item().AlignCenter().Text(x =>
                        {
                            x.Span("Generated by CrushEase Ledger on ");
                            x.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                        });
                        col.Item().PaddingTop(5).AlignCenter().Text(x =>
                        {
                            x.Span("Built by NMD").FontSize(7).Italic().FontColor(Colors.Grey.Medium);
                        });
                    });
                });
            });
            
            string receiptsFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "CrushEase Invoices",
                "Receipts"
            );
            Directory.CreateDirectory(receiptsFolder);
            
            string fileName = $"{receiptNumber.Replace("/", "-")}_{vendor.VendorName.Replace(" ", "_")}_Receipt.pdf";
            string filePath = Path.Combine(receiptsFolder, fileName);
            
            document.GeneratePdf(filePath);
            
            if (existingReceipt == null)
            {
                var metadata = new InvoiceMetadata
                {
                    InvoiceNumber = receiptNumber,
                    TransactionType = "PurchaseReceipt",
                    TransactionId = purchase.PurchaseId,
                    GeneratedDate = DateTime.Now,
                    GeneratedBy = "System",
                    FilePath = filePath
                };
                InvoiceMetadataRepository.Save(metadata);
            }
            
            Logger.LogInfo($"Purchase receipt generated: {receiptNumber}");
            
            return new InvoiceResult
            {
                Success = true,
                InvoiceNumber = receiptNumber,
                FilePath = filePath,
                PdfDocument = document
            };
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate purchase receipt");
            return new InvoiceResult
            {
                Success = false,
                ErrorMessage = $"Error generating purchase receipt: {ex.Message}"
            };
        }
    }
    
    private static void ComposeReceiptHeader(IContainer container, CompanySettings settings, string receiptNumber, DateTime purchaseDate)
    {
        container.Column(column =>
        {
            column.Spacing(3);
            
            // Company details - compact header
            column.Item().Column(col =>
            {
                col.Item().AlignCenter().Text(settings.CompanyName)
                    .Bold()
                    .FontSize(16);
                
                if (!string.IsNullOrEmpty(settings.Address))
                    col.Item().AlignCenter().Text(settings.Address).FontSize(8);
                
                var contactInfo = new List<string>();
                if (!string.IsNullOrEmpty(settings.Phone))
                    contactInfo.Add($"Ph: {settings.Phone}");
                if (!string.IsNullOrEmpty(settings.Email))
                    contactInfo.Add(settings.Email);
                
                if (contactInfo.Count > 0)
                    col.Item().AlignCenter().Text(string.Join(" | ", contactInfo)).FontSize(8);
                
                if (!string.IsNullOrEmpty(settings.GSTNumber))
                    col.Item().AlignCenter().Text($"GSTIN: {settings.GSTNumber}").FontSize(8);
            });
            
            column.Item().PaddingTop(3).LineHorizontal(1).LineColor(Colors.Black);
            
            // Bill title and details - compact
            column.Item().PaddingVertical(5).Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("PURCHASE BILL").FontSize(18).Bold();
                });
                row.RelativeItem().AlignRight().Column(c =>
                {
                    c.Item().AlignRight().Text($"Bill No: {receiptNumber}").FontSize(9).Bold();
                    c.Item().AlignRight().Text($"Date: {purchaseDate:dd-MMM-yyyy}").FontSize(9);
                });
            });
            
            column.Item().LineHorizontal(1).LineColor(Colors.Black);
        });
    }
    
    private static void ComposePurchaseReceiptContent(IContainer container, Purchase purchase, Vendor vendor, Material material, CompanySettings settings)
    {
        container.Column(column =>
        {
            column.Spacing(8);
            
            // Vendor Information - compact
            column.Item().Row(row =>
            {
                row.ConstantItem(100).Text("Vendor Name:").Bold().FontSize(9);
                row.RelativeItem().Text(vendor.VendorName).FontSize(10);
            });
            
            if (!string.IsNullOrEmpty(vendor.Contact))
            {
                column.Item().Row(row =>
                {
                    row.ConstantItem(100).Text("Contact:").Bold().FontSize(9);
                    row.RelativeItem().Text(vendor.Contact).FontSize(9);
                });
            }
            
            if (!string.IsNullOrEmpty(purchase.VendorSite))
            {
                column.Item().Row(row =>
                {
                    row.ConstantItem(100).Text("Site:").Bold().FontSize(9);
                    row.RelativeItem().Text(purchase.VendorSite).FontSize(9);
                });
            }
            
            column.Item().PaddingTop(5).LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);
            
            // Transaction Details Table - clean and compact
            column.Item().PaddingTop(8).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1.5f);
                    columns.RelativeColumn(1.5f);
                    columns.RelativeColumn(1.5f);
                });
                
                table.Header(header =>
                {
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                        .Text("Description").Bold().FontSize(9);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                        .AlignCenter().Text("Quantity").Bold().FontSize(9);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                        .AlignCenter().Text("Rate (₹)").Bold().FontSize(9);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                        .AlignRight().Text("Amount (₹)").Bold().FontSize(9);
                });
                
                // Material row
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(5).Column(col =>
                {
                    col.Item().Text(material.MaterialName).FontSize(9);
                    col.Item().Text($"Vehicle: {purchase.VehicleNo}").FontSize(7).Italic();
                });
                
                string qtyDisplay = purchase.InputUnit == "MT" 
                    ? $"{purchase.InputQuantity:F2} MT\n({purchase.CalculatedCFT:F2} CFT)"
                    : $"{purchase.CalculatedCFT:F2} CFT";
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                    .AlignCenter().Text(qtyDisplay).FontSize(8);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                    .AlignCenter().Text($"{purchase.Rate:F2}").FontSize(9);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(5)
                    .AlignRight().Text($"{purchase.Amount:F2}").FontSize(9).Bold();
            });
            
            // Total Amount - clean box
            column.Item().PaddingTop(5).Border(1).BorderColor(Colors.Black).Padding(8).Row(row =>
            {
                row.RelativeItem().Text("TOTAL AMOUNT:").Bold().FontSize(11);
                row.ConstantItem(120).AlignRight().Text($"₹ {purchase.Amount:N2}").Bold().FontSize(12);
            });
            
            // Amount in words
            column.Item().PaddingTop(3).Text($"Amount in words: {ConvertAmountToWords(purchase.Amount)}").FontSize(8).Italic();
            
            // Vendor Acknowledgement Section - clear and professional
            column.Item().PaddingTop(15).Border(1).BorderColor(Colors.Black).Padding(10).Column(col =>
            {
                col.Item().Text("VENDOR ACKNOWLEDGEMENT").Bold().FontSize(10);
                col.Item().PaddingTop(5).Text($"I acknowledge receipt of ₹{purchase.Amount:N2} (Rupees {ConvertAmountToWords(purchase.Amount)}) from {settings.CompanyName} against the supply of {material.MaterialName} as detailed above.").FontSize(8);
                
                col.Item().PaddingTop(15).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("Date: ______________").FontSize(8);
                    });
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().AlignRight().Text("Vendor's Signature").FontSize(8);
                        c.Item().PaddingTop(20).AlignRight().LineHorizontal(1).LineColor(Colors.Black);
                        c.Item().AlignRight().Text(vendor.VendorName).FontSize(7).Italic();
                    });
                });
            });
            
            // Authorized Signature
            column.Item().PaddingTop(20).Row(row =>
            {
                row.RelativeItem();
                row.ConstantItem(150).Column(col =>
                {
                    col.Item().AlignCenter().Text("For " + settings.CompanyName).FontSize(8);
                    col.Item().PaddingTop(20).BorderTop(1).BorderColor(Colors.Black);
                    col.Item().AlignCenter().Text("Authorized Signatory").FontSize(8);
                });
            });
        });
    }
    
    private static string ConvertAmountToWords(decimal amount)
    {
        // Simple implementation - can be enhanced
        var rupees = (long)Math.Floor(amount);
        var paise = (int)((amount - rupees) * 100);
        
        if (rupees == 0 && paise == 0)
            return "Zero Rupees Only";
        
        string result = NumberToWords(rupees) + " Rupees";
        if (paise > 0)
            result += $" and {NumberToWords(paise)} Paise";
        result += " Only";
        
        return result;
    }
    
    private static string NumberToWords(long number)
    {
        if (number == 0) return "Zero";
        
        if (number < 0) return "Minus " + NumberToWords(Math.Abs(number));
        
        string words = "";
        
        if (number / 10000000 > 0)
        {
            words += NumberToWords(number / 10000000) + " Crore ";
            number %= 10000000;
        }
        
        if (number / 100000 > 0)
        {
            words += NumberToWords(number / 100000) + " Lakh ";
            number %= 100000;
        }
        
        if (number / 1000 > 0)
        {
            words += NumberToWords(number / 1000) + " Thousand ";
            number %= 1000;
        }
        
        if (number / 100 > 0)
        {
            words += NumberToWords(number / 100) + " Hundred ";
            number %= 100;
        }
        
        if (number > 0)
        {
            var unitsMap = new[] { "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
                "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen" };
            var tensMap = new[] { "Zero", "Ten", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety" };
            
            if (number < 20)
                words += unitsMap[number];
            else
            {
                words += tensMap[number / 10];
                if ((number % 10) > 0)
                    words += " " + unitsMap[number % 10];
            }
        }
        
        return words.Trim();
    }
    
    private static void ComposePurchaseContent(IContainer container, Purchase purchase, Vendor vendor, Material material, CompanySettings settings)
    {
        container.Column(column =>
        {
            column.Spacing(6);
            
            // Vendor section - compact
            column.Item().Border(1).BorderColor(Colors.Black).Padding(5).Column(col =>
            {
                col.Item().Text("VENDOR:").Bold().FontSize(8);
                col.Item().PaddingTop(2).Column(c =>
                {
                    c.Item().Text(vendor.VendorName).FontSize(9).Bold();
                    if (!string.IsNullOrEmpty(vendor.Contact))
                        c.Item().Text($"Contact: {vendor.Contact}").FontSize(7);
                    if (!string.IsNullOrEmpty(purchase.VendorSite))
                        c.Item().Text($"Site: {purchase.VendorSite}").FontSize(7);
                });
            });
            
            // Purchase items table - compact
            column.Item().PaddingTop(5).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                });
                
                table.Header(header =>
                {
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .Text("Description").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignCenter().Text("Qty").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignCenter().Text("Rate").Bold().FontSize(8);
                    header.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                        .AlignRight().Text("Amount").Bold().FontSize(8);
                });
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4).Column(col =>
                {
                    col.Item().Text(material.MaterialName).Bold().FontSize(8);
                    col.Item().Text($"Vehicle: {purchase.VehicleNo}").FontSize(6).Italic();
                    
                    string unitInfo = purchase.InputUnit == "MT" 
                        ? $"{purchase.InputQuantity:F2} MT ({purchase.CalculatedCFT:F2} CFT)"
                        : $"{purchase.InputQuantity:F2} CFT";
                    col.Item().Text(unitInfo).FontSize(6).Italic();
                });
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignCenter().Text($"{purchase.Quantity:F2}").FontSize(8);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignCenter().Text($"₹{purchase.Rate:F2}").FontSize(8);
                
                table.Cell().Border(1).BorderColor(Colors.Black).Padding(4)
                    .AlignRight().Text($"₹{purchase.Amount:F2}").Bold().FontSize(8);
            });
            
            // Total - compact
            column.Item().PaddingTop(3).Border(1).BorderColor(Colors.Black).Padding(5).Row(row =>
            {
                row.RelativeItem().Text("TOTAL:").Bold().FontSize(10);
                row.ConstantItem(80).AlignRight().Text($"₹{purchase.Amount:F2}").Bold().FontSize(10);
            });
            
            // Payment terms - compact
            column.Item().PaddingTop(8).Column(col =>
            {
                col.Item().Text("Payment Terms:").Bold().FontSize(7);
                col.Item().PaddingTop(2).Text(settings.PaymentTerms).FontSize(7);
            });
            
            if (!string.IsNullOrEmpty(settings.TermsAndConditions))
            {
                column.Item().PaddingTop(6).Column(col =>
                {
                    col.Item().Text("Terms & Conditions:").Bold().FontSize(7);
                    col.Item().PaddingTop(2).Text(settings.TermsAndConditions).FontSize(6);
                });
            }
            
            column.Item().PaddingTop(15).Row(row =>
            {
                row.RelativeItem();
                row.ConstantItem(100).Column(col =>
                {
                    col.Item().AlignCenter().Text("Authorized Sign").FontSize(7);
                    col.Item().PaddingTop(15).BorderTop(1).BorderColor(Colors.Black);
                });
            });
        });
    }
}

/// <summary>
/// Result of invoice generation
/// </summary>
public class InvoiceResult
{
    public bool Success { get; set; }
    public string? InvoiceNumber { get; set; }
    public string? FilePath { get; set; }
    public string? ErrorMessage { get; set; }
    public IDocument? PdfDocument { get; set; }
}
