using CrushEase.Data;
using CrushEase.Models;
using CrushEase.Utils;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CrushEase.Services;

/// <summary>
/// Service for generating professional PDF invoices
/// </summary>
public static class InvoiceGenerator
{
    static InvoiceGenerator()
    {
        // Set QuestPDF license to Community (free for open-source/personal use)
        QuestPDF.Settings.License = LicenseType.Community;
    }
    
    /// <summary>
    /// Generate invoice for a sale transaction
    /// </summary>
    public static InvoiceResult GenerateSaleInvoice(Sale sale)
    {
        try
        {
            // Get company settings
            var companySettings = CompanySettingsRepository.Get();
            if (companySettings == null || string.IsNullOrEmpty(companySettings.CompanyName))
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Company settings not configured. Please configure company details first." 
                };
            }
            
            // Get buyer details
            var buyer = BuyerRepository.GetById(sale.BuyerId);
            if (buyer == null)
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Buyer not found." 
                };
            }
            
            // Get material details
            var material = MaterialRepository.GetById(sale.MaterialId);
            if (material == null)
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Material not found." 
                };
            }
            
            // Generate invoice number
            var existingInvoice = InvoiceMetadataRepository.GetByTransaction("Sale", sale.SaleId);
            string invoiceNumber;
            
            if (existingInvoice != null)
            {
                invoiceNumber = existingInvoice.InvoiceNumber;
            }
            else
            {
                invoiceNumber = InvoiceMetadataRepository.GenerateInvoiceNumber(companySettings.InvoicePrefix);
            }
            
            // Create PDF
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Segoe UI"));
                    
                    page.Header().Element(c => ComposeHeader(c, companySettings, invoiceNumber, sale.SaleDate));
                    page.Content().Element(c => ComposeSaleContent(c, sale, buyer, material, companySettings));
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by CrushEase Ledger on ");
                        x.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                    });
                });
            });
            
            // Generate file path
            string invoicesFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "CrushEase Invoices"
            );
            Directory.CreateDirectory(invoicesFolder);
            
            string fileName = $"{invoiceNumber.Replace("/", "-")}_{buyer.BuyerName.Replace(" ", "_")}.pdf";
            string filePath = Path.Combine(invoicesFolder, fileName);
            
            // Save PDF
            document.GeneratePdf(filePath);
            
            // Save metadata if new invoice
            if (existingInvoice == null)
            {
                var metadata = new InvoiceMetadata
                {
                    InvoiceNumber = invoiceNumber,
                    TransactionType = "Sale",
                    TransactionId = sale.SaleId,
                    GeneratedDate = DateTime.Now,
                    GeneratedBy = "System",
                    FilePath = filePath
                };
                InvoiceMetadataRepository.Save(metadata);
            }
            
            Logger.LogInfo($"Invoice generated: {invoiceNumber}");
            
            return new InvoiceResult
            {
                Success = true,
                InvoiceNumber = invoiceNumber,
                FilePath = filePath,
                PdfDocument = document
            };
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate invoice");
            return new InvoiceResult
            {
                Success = false,
                ErrorMessage = $"Error generating invoice: {ex.Message}"
            };
        }
    }
    
    private static void ComposeHeader(IContainer container, CompanySettings settings, string invoiceNumber, DateTime invoiceDate)
    {
        container.Column(column =>
        {
            column.Spacing(10);
            
            // Company info and logo row
            column.Item().Row(row =>
            {
                // Left: Company details
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(settings.CompanyName)
                        .FontSize(18)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);
                    
                    if (!string.IsNullOrEmpty(settings.Address))
                        col.Item().Text(settings.Address).FontSize(9);
                    
                    if (!string.IsNullOrEmpty(settings.Phone))
                        col.Item().Text($"Phone: {settings.Phone}").FontSize(9);
                    
                    if (!string.IsNullOrEmpty(settings.Email))
                        col.Item().Text($"Email: {settings.Email}").FontSize(9);
                    
                    if (!string.IsNullOrEmpty(settings.GSTNumber))
                        col.Item().Text($"GST: {settings.GSTNumber}").FontSize(9);
                });
                
                // Right: Logo (if exists)
                if (settings.LogoImage != null && settings.LogoImage.Length > 0)
                {
                    row.ConstantItem(100).Image(settings.LogoImage).FitArea();
                }
            });
            
            // Divider
            column.Item().LineHorizontal(2).LineColor(Colors.Blue.Darken2);
            
            // Invoice title and details
            column.Item().PaddingVertical(10).Column(col =>
            {
                col.Item().AlignCenter().Text("INVOICE")
                    .FontSize(22)
                    .Bold()
                    .FontColor(Colors.Blue.Darken3);
                
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text($"Invoice No: {invoiceNumber}").Bold();
                        c.Item().Text($"Invoice Date: {DateTime.Now:dd-MMM-yyyy}");
                    });
                    
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text($"Sale Date: {invoiceDate:dd-MMM-yyyy}").Bold();
                    });
                });
            });
        });
    }
    
    private static void ComposeSaleContent(IContainer container, Sale sale, Buyer buyer, Material material, CompanySettings settings)
    {
        container.Column(column =>
        {
            column.Spacing(15);
            
            // Bill To section
            column.Item().Background(Colors.Grey.Lighten3).Padding(10).Column(col =>
            {
                col.Item().Text("BILL TO:").Bold().FontSize(11);
                col.Item().PaddingTop(5).Column(c =>
                {
                    c.Item().Text(buyer.BuyerName).FontSize(12).Bold();
                    if (!string.IsNullOrEmpty(buyer.Contact))
                        c.Item().Text($"Contact: {buyer.Contact}");
                });
            });
            
            // Invoice items table
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3); // Description
                    columns.RelativeColumn(1); // Quantity
                    columns.RelativeColumn(1); // Rate
                    columns.RelativeColumn(1); // Amount
                });
                
                // Header
                table.Header(header =>
                {
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Description").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Quantity").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Rate").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .AlignRight().Text("Amount").FontColor(Colors.White).Bold();
                });
                
                // Data row
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8).Column(col =>
                {
                    col.Item().Text(material.MaterialName).Bold();
                    col.Item().PaddingTop(3).Text($"Vehicle: {sale.VehicleNo}").FontSize(9).Italic();
                    
                    // Show unit details
                    string unitInfo = sale.InputUnit == "MT" 
                        ? $"Unit: {sale.InputQuantity:F2} MT (= {sale.CalculatedCFT:F2} CFT)"
                        : $"Unit: {sale.InputQuantity:F2} CFT";
                    col.Item().Text(unitInfo).FontSize(9).Italic();
                });
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"{sale.Quantity:F2}");
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"₹{sale.Rate:F2}");
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"₹{sale.Amount:F2}").Bold();
            });
            
            // Totals section
            column.Item().AlignRight().Width(200).Column(col =>
            {
                col.Item().BorderTop(1).BorderColor(Colors.Grey.Medium).PaddingTop(5);
                
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("Subtotal:");
                    row.ConstantItem(100).AlignRight().Text($"₹{sale.Amount:F2}");
                });
                
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.RelativeItem().Text("TOTAL:").Bold().FontSize(12);
                    row.ConstantItem(100).AlignRight().Text($"₹{sale.Amount:F2}").Bold().FontSize(12);
                });
            });
            
            // Payment terms
            column.Item().PaddingTop(20).Column(col =>
            {
                col.Item().Text("Payment Terms:").Bold();
                col.Item().PaddingTop(5).Text(settings.PaymentTerms);
            });
            
            // Terms and conditions (if any)
            if (!string.IsNullOrEmpty(settings.TermsAndConditions))
            {
                column.Item().PaddingTop(15).Column(col =>
                {
                    col.Item().Text("Terms & Conditions:").Bold().FontSize(9);
                    col.Item().PaddingTop(5).Text(settings.TermsAndConditions).FontSize(8);
                });
            }
            
            // Signature section
            column.Item().PaddingTop(30).Row(row =>
            {
                row.RelativeItem();
                row.RelativeItem().Column(col =>
                {
                    col.Item().AlignCenter().Text("Authorized Signature").FontSize(9);
                    col.Item().PaddingTop(25).BorderTop(1).BorderColor(Colors.Black);
                });
            });
        });
    }
    
    /// <summary>
    /// Generate invoice for a purchase transaction
    /// </summary>
    public static InvoiceResult GeneratePurchaseInvoice(Purchase purchase)
    {
        try
        {
            var companySettings = CompanySettingsRepository.Get();
            if (companySettings == null || string.IsNullOrEmpty(companySettings.CompanyName))
            {
                return new InvoiceResult 
                { 
                    Success = false, 
                    ErrorMessage = "Company settings not configured." 
                };
            }
            
            var vendor = VendorRepository.GetById(purchase.VendorId);
            if (vendor == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Vendor not found." };
            }
            
            var material = MaterialRepository.GetById(purchase.MaterialId);
            if (material == null)
            {
                return new InvoiceResult { Success = false, ErrorMessage = "Material not found." };
            }
            
            var existingInvoice = InvoiceMetadataRepository.GetByTransaction("Purchase", purchase.PurchaseId);
            string invoiceNumber = existingInvoice?.InvoiceNumber 
                ?? InvoiceMetadataRepository.GenerateInvoiceNumber(companySettings.InvoicePrefix);
            
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Segoe UI"));
                    
                    page.Header().Element(c => ComposeHeader(c, companySettings, invoiceNumber, purchase.PurchaseDate));
                    page.Content().Element(c => ComposePurchaseContent(c, purchase, vendor, material, companySettings));
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by CrushEase Ledger on ");
                        x.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8);
                    });
                });
            });
            
            string invoicesFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "CrushEase Invoices"
            );
            Directory.CreateDirectory(invoicesFolder);
            
            string fileName = $"{invoiceNumber.Replace("/", "-")}_{vendor.VendorName.Replace(" ", "_")}_Purchase.pdf";
            string filePath = Path.Combine(invoicesFolder, fileName);
            
            document.GeneratePdf(filePath);
            
            if (existingInvoice == null)
            {
                var metadata = new InvoiceMetadata
                {
                    InvoiceNumber = invoiceNumber,
                    TransactionType = "Purchase",
                    TransactionId = purchase.PurchaseId,
                    GeneratedDate = DateTime.Now,
                    GeneratedBy = "System",
                    FilePath = filePath
                };
                InvoiceMetadataRepository.Save(metadata);
            }
            
            Logger.LogInfo($"Purchase invoice generated: {invoiceNumber}");
            
            return new InvoiceResult
            {
                Success = true,
                InvoiceNumber = invoiceNumber,
                FilePath = filePath,
                PdfDocument = document
            };
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Failed to generate purchase invoice");
            return new InvoiceResult
            {
                Success = false,
                ErrorMessage = $"Error generating purchase invoice: {ex.Message}"
            };
        }
    }
    
    private static void ComposePurchaseContent(IContainer container, Purchase purchase, Vendor vendor, Material material, CompanySettings settings)
    {
        container.Column(column =>
        {
            column.Spacing(15);
            
            // Vendor section
            column.Item().Background(Colors.Grey.Lighten3).Padding(10).Column(col =>
            {
                col.Item().Text("VENDOR:").Bold().FontSize(11);
                col.Item().PaddingTop(5).Column(c =>
                {
                    c.Item().Text(vendor.VendorName).FontSize(12).Bold();
                    if (!string.IsNullOrEmpty(vendor.Contact))
                        c.Item().Text($"Contact: {vendor.Contact}");
                    if (!string.IsNullOrEmpty(purchase.VendorSite))
                        c.Item().Text($"Site: {purchase.VendorSite}");
                });
            });
            
            // Purchase items table
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                });
                
                table.Header(header =>
                {
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Description").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Quantity").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .Text("Rate").FontColor(Colors.White).Bold();
                    header.Cell().Background(Colors.Blue.Darken2).Padding(8)
                        .AlignRight().Text("Amount").FontColor(Colors.White).Bold();
                });
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8).Column(col =>
                {
                    col.Item().Text(material.MaterialName).Bold();
                    col.Item().PaddingTop(3).Text($"Vehicle: {purchase.VehicleNo}").FontSize(9).Italic();
                    
                    string unitInfo = purchase.InputUnit == "MT" 
                        ? $"Unit: {purchase.InputQuantity:F2} MT (= {purchase.CalculatedCFT:F2} CFT)"
                        : $"Unit: {purchase.InputQuantity:F2} CFT";
                    col.Item().Text(unitInfo).FontSize(9).Italic();
                });
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"{purchase.Quantity:F2}");
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"₹{purchase.Rate:F2}");
                
                table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(8)
                    .AlignRight().Text($"₹{purchase.Amount:F2}").Bold();
            });
            
            // Totals
            column.Item().AlignRight().Width(200).Column(col =>
            {
                col.Item().BorderTop(1).BorderColor(Colors.Grey.Medium).PaddingTop(5);
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("Subtotal:");
                    row.ConstantItem(100).AlignRight().Text($"₹{purchase.Amount:F2}");
                });
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.RelativeItem().Text("TOTAL:").Bold().FontSize(12);
                    row.ConstantItem(100).AlignRight().Text($"₹{purchase.Amount:F2}").Bold().FontSize(12);
                });
            });
            
            // Payment terms
            column.Item().PaddingTop(20).Column(col =>
            {
                col.Item().Text("Payment Terms:").Bold();
                col.Item().PaddingTop(5).Text(settings.PaymentTerms);
            });
            
            if (!string.IsNullOrEmpty(settings.TermsAndConditions))
            {
                column.Item().PaddingTop(15).Column(col =>
                {
                    col.Item().Text("Terms & Conditions:").Bold().FontSize(9);
                    col.Item().PaddingTop(5).Text(settings.TermsAndConditions).FontSize(8);
                });
            }
            
            column.Item().PaddingTop(30).Row(row =>
            {
                row.RelativeItem();
                row.RelativeItem().Column(col =>
                {
                    col.Item().AlignCenter().Text("Authorized Signature").FontSize(9);
                    col.Item().PaddingTop(25).BorderTop(1).BorderColor(Colors.Black);
                });
            });
        });
    }
}

/// <summary>
/// Result of invoice generation
/// </summary>
public class InvoiceResult
{
    public bool Success { get; set; }
    public string? InvoiceNumber { get; set; }
    public string? FilePath { get; set; }
    public string? ErrorMessage { get; set; }
    public IDocument? PdfDocument { get; set; }
}
